<?php
/**
 * Copyright (c) 2025 KOUNT, INC.
 * See COPYING.txt for license details.
 */

/** @var $block \Kount\Kount360\Block\Adminhtml\Order\View\Tab\Kount */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?= $block->escapeHtml(__('Kount')) ?></h4>
    </div>
    <div class="fieldset fieldset-wide">
        <div class="fieldset">
            <table cellspacing="0" class="form-list admin__table-primary">
                <tr>
                    <td class="label">
                        <label><?= $block->escapeHtml(__('Omniscore')) ?></label>
                        <p><i><?= $block->escapeHtml(__('Higher indicates less risk')) ?></i></p>
                    </td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getOmniscore()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('Decision Status')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getRisResponse()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('Rules Triggered')) ?></label></td>
                    <td class="value"><strong><?= nl2br($block->escapeHtml(__($block->getRisRules()))) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('Transaction ID')) ?></label></td>
                    <td class="value">
                        <?php if ($block->getRisTransactionId()): ?>
                            <strong><a href="<?= $block->escapeHtmlAttr($block->getAWCUrl()) ?>" target="_blank"><?= $block->escapeHtml($block->getRisTransactionId()) ?></a></strong>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('Persona Country')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getRisGeox()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('Device Country')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getRisCountry()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= __($block->escapeHtml('Data Collector Present')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getRisKaptcha()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('Cards associated with Persona')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getRisCards()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('Emails associated with Persona')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getRisEmails()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('Devices associated with Persona')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getRisDevices()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('IP Address')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getIpAddress()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('IP City')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getIpCity()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('Network Type')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getNetw()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('Is Mobile Device')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getMobileDevice()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?= $block->escapeHtml(__('Mobile Type')) ?></label></td>
                    <td class="value"><strong><?= $block->escapeHtml($block->getMobileType()) ?></strong></td>
                </tr>
            </table>
        </div>
    </div>
</div>
